before_script:
- pip install tox setuptools

flake8:
  image: "python:3.9"
  cache:
    key: flake8
    paths:
    - .tox/flake8
  script:
  - tox -e flake8

check_rst:
  image: "python:3.9"
  cache:
    key: check_rst
    paths:
    - .tox/check_rst
  script:
  - tox -e check_rst

py27-django111:
  image: "python:2.7"
  cache:
    key: py27-django111
    paths:
    - .tox/py27-django111
  script:
  - tox -e py27-django111

py35-django111:
  image: "python:3.5"
  cache:
    key: py35-django111
    paths:
    - .tox/py35-django111
  script:
  - tox -e py35-django111

py36-django111:
  image: "python:3.6"
  cache:
    key: py36-django111
    paths:
    - .tox/py36-django111
  script:
  - tox -e py36-django111

py37-django22:
  image: "python:3.7"
  cache:
    key: py37-django22
    paths:
    - .tox/py37-django22
  script:
  - tox -e py37-django22

py38-django22:
  image: "python:3.8"
  cache:
    key: py38-django22
    paths:
    - .tox/py38-django22
  script:
  - tox -e py38-django22

py38-django30:
  image: "python:3.8"
  cache:
    key: py38-django30
    paths:
    - .tox/py38-django30
  script:
  - tox -e py38-django30

py38-django31:
  image: "python:3.8"
  cache:
    key: py38-django31
    paths:
    - .tox/py38-django31
  script:
  - tox -e py38-django31

py39-django22:
  image: "python:3.9"
  cache:
    key: py39-django22
    paths:
    - .tox/py39-django22
  script:
  - tox -e py39-django22

py39-django30:
  image: "python:3.9"
  cache:
    key: py39-django30
    paths:
    - .tox/py39-django30
  script:
  - tox -e py39-django30

py39-django31:
  image: "python:3.9"
  cache:
    key: py39-django31
    paths:
    - .tox/py39-django31
  script:
  - tox -e py39-django31

coverage:
  image: "python:3.9"
  cache:
    key: coverage
    paths:
    - .tox/coverage
  script:
  - tox -e coverage
